apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-flask-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rajeshgoyalg/helm-charts.git
    targetRevision: main
    path: python-flask-app
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true