apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    app: python-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
        - name: python-flask-app
          image: rajeshgoyalg/python-flask-app:latest   # This will be replaced later with a versioned tag
          resources:
            limits:
              cpu: "500m"    # Half a CPU core
              memory: "512Mi" # 512 MB memory
            requests:
              cpu: "200m"    # Request 0.2 CPU cores
              memory: "256Mi" # Request 256 MB memory
          ports:
            - containerPort: 5000